# 指定编译器选项
CC = gcc
WORKDIR = .
CFLAGS = -Wall -g
INCFLAGS = -I$(WORKDIR)

OBJS = socketutil.o poolsocket.o socketlog.o
LIB = libsocket.so

$(LIB):$(OBJS)
	$(CC) -shared -fPIC $^ -o $@

.c.o:
	$(CC) $(CFLAGS) $(INCFLAGS) -c $< -o $@

.PHONY:clean

clean:
	rm socketutil.o poolsocket.o socketlog.o libsocket.so